name: krushibandhu
description: "Smart Agriculture Platform - KrushiBandhu"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.8.0

  # Voice Assistant
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2

  # QR Scanner
  mobile_scanner: ^5.2.3
  image_picker: ^1.1.2

  # QR Code Generator
  qr_flutter: ^4.1.0

  # Share Booking
  share_plus: ^11.1.0

  # Online Payment
  razorpay_flutter: ^1.4.0

  # Local Database
  sqflite: ^2.4.2
  path: ^1.9.1

  # State Management
  provider: ^6.1.2

  # Local Storage
  shared_preferences: ^2.2.3

  # Date Formatting
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true