// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVR9n3B9MpEfDGbGxNHP4-6RIdLuJcjHM',
    appId: '1:764037151303:web:d8196902a979a15e124f62',
    messagingSenderId: '764037151303',
    projectId: 'krushibandhu-8840a',
    authDomain: 'krushibandhu-8840a.firebaseapp.com',
    storageBucket: 'krushibandhu-8840a.firebasestorage.app',
    measurementId: 'G-MQFSYSE2JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjrWpzmPBgZ1H0OHs7TzcP6KDVQhMR3Oc',
    appId: '1:764037151303:android:d8183ec1812cd1b6124f62',
    messagingSenderId: '764037151303',
    projectId: 'krushibandhu-8840a',
    storageBucket: 'krushibandhu-8840a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO1tO20J72JBI7OfY76AE7lON0j0vGcaA',
    appId: '1:764037151303:ios:2badcd659af40f03124f62',
    messagingSenderId: '764037151303',
    projectId: 'krushibandhu-8840a',
    storageBucket: 'krushibandhu-8840a.firebasestorage.app',
    iosBundleId: 'com.example.krushibandhu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO1tO20J72JBI7OfY76AE7lON0j0vGcaA',
    appId: '1:764037151303:ios:2badcd659af40f03124f62',
    messagingSenderId: '764037151303',
    projectId: 'krushibandhu-8840a',
    storageBucket: 'krushibandhu-8840a.firebasestorage.app',
    iosBundleId: 'com.example.krushibandhu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVR9n3B9MpEfDGbGxNHP4-6RIdLuJcjHM',
    appId: '1:764037151303:web:5413a5ffdacf9e22124f62',
    messagingSenderId: '764037151303',
    projectId: 'krushibandhu-8840a',
    authDomain: 'krushibandhu-8840a.firebaseapp.com',
    storageBucket: 'krushibandhu-8840a.firebasestorage.app',
    measurementId: 'G-QBR84F0CJF',
  );
}
